# Generated by Django 5.1.4 on 2025-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_stock_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cess_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('igst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sale_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low_level_limit', models.IntegerField(blank=True, null=True)),
                ('general_option', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('print_description', models.BooleanField(default=False)),
                ('one_click_sale', models.BooleanField(default=False)),
                ('enable_tracking', models.BooleanField(default=False)),
                ('print_serial_no', models.BooleanField(default=False)),
                ('not_for_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
