# Generated by Django 5.1.4 on 2025-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cess_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cgst_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='enable_tracking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_sac_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='igst_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_level_limit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='not_for_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='one_click_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_stock_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='print_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='print_serial_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sgst_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=100),
        ),
    ]
