# Generated by Django 5.1.4 on 2025-01-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0003_pricedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAndUnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('opening_stock', models.IntegerField()),
                ('opening_stock_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_and_unit_details', to='Addproduct.product')),
            ],
        ),
    ]
