# Generated by Django 5.1.4 on 2025-01-20 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0004_stockandunitdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low_level_limit', models.IntegerField()),
                ('select_general', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_details', to='Addproduct.product')),
            ],
        ),
    ]
