# Generated by Django 5.1.4 on 2025-01-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('under', models.CharField(default='Primary', max_length=100)),
                ('should_quantities_be_added', models.BooleanField(default=False)),
                ('set_alter_gst_details', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('formal_name', models.CharField(max_length=100)),
                ('uqc', models.IntegerField()),
                ('number_of_decimal_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gst_applicability', models.CharField(blank=True, choices=[('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable')], max_length=100)),
                ('set_alter_gst_details', models.BooleanField(default=False)),
                ('type_of_supply', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], default='Goods', max_length=50)),
                ('rate_of_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_quantity', models.IntegerField(blank=True, null=True)),
                ('rate_per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockgroup')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unitcreation')),
            ],
        ),
    ]
