# Generated by Django 5.1.4 on 2025-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgroup',
            name='set_alter_gst_details',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='should_quantities_be_added',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='gst_applicability',
            field=models.CharField(choices=[('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='set_alter_gst_details',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='under',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='units',
            field=models.CharField(max_length=100),
        ),
    ]
