# Generated by Django 5.1.4 on 2025-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stockgroup_set_alter_gst_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='UnitCreation',
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='set_alter_gst_details',
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='should_quantities_be_added',
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='gst_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='quantities_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='under',
            field=models.CharField(choices=[('primary', 'Primary')], max_length=255),
        ),
    ]
