# Generated by Django 5.1.4 on 2025-01-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_stockitem_delete_unitcreation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('formal_name', models.CharField(max_length=255)),
                ('unit_quantity_code', models.IntegerField()),
                ('number_of_decimal_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_applicability', models.BooleanField(default=False)),
                ('gst_details', models.BooleanField(default=False)),
                ('type_of_supply', models.CharField(default='Goods', max_length=50)),
                ('rate_of_duty', models.FloatField()),
                ('opening_balance_quantity', models.IntegerField()),
                ('opening_balance_rate_per', models.FloatField()),
                ('opening_balance_value', models.FloatField()),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockgroup')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unit')),
            ],
        ),
    ]
