# Generated by Django 4.2.16 on 2025-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscriptionplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
