# Generated by Django 5.1.4 on 2025-01-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_unit_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Compound', 'Compound')], max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('formal_name', models.CharField(max_length=50)),
                ('uqc', models.IntegerField()),
                ('decimal_places', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='units',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='gst_details',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='gst_details',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='opening_balance_quantity',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='opening_balance_rate_per',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='opening_balance_value',
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='alter_gst_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='alter_gst_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='opening_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='under',
            field=models.CharField(default='Primary', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='gst_applicability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='rate_of_duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='myapp.stockgroup'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
