# Generated by Django 5.1.4 on 2025-01-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_unitcreation_alter_stockitem_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='under',
        ),
        migrations.DeleteModel(
            name='UnitCreation',
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='alter_gst_details',
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='set_alter_gst_details',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='quantities_added',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='myapp.stockgroup'),
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
