# Generated by Django 4.2.16 on 2025-02-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_suppilerlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuppilerList',
            new_name='SupplierList',
        ),
    ]
