# Generated by Django 5.1.4 on 2025-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_stockitem_under_delete_unitcreation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('Simple', 'Simple'), ('Compound', 'Compound')], max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('formal_name', models.CharField(max_length=50)),
                ('uqc', models.IntegerField()),
                ('decimal_places', models.IntegerField(default=0)),
            ],
        ),
    ]
