# Generated by Django 4.2.16 on 2025-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_suppilerlist_supplierlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierlist',
            name='suppiler_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
