# Generated by Django 5.1.4 on 2025-01-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_unitcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('under', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('gst_applicability', models.CharField(default='Yes', max_length=3)),
                ('set_alter_gst_details', models.CharField(default='Yes', max_length=3)),
                ('type_of_supply', models.CharField(default='Goods', max_length=50)),
                ('rate_of_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_quantity', models.IntegerField(default=0)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='myapp.stockgroup')),
            ],
        ),
    ]
