# Generated by Django 4.2.16 on 2025-02-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_supplierlist_suppiler_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierlist',
            old_name='suppiler_name',
            new_name='supplier_name',
        ),
    ]
