# Generated by Django 5.1.4 on 2025-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxability', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Exempt', 'Exempt'), ('Nil Rated', 'Nil Rated'), ('Taxable', 'Taxable')], default=None, max_length=20, null=True)),
                ('applicable_from', models.DateField(blank=True, default=None, null=True)),
                ('tax_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('integrated_tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
            ],
        ),
    ]
