# Generated by Django 4.2.16 on 2025-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_suppiler_name_supplierlist_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
