# Generated by Django 4.2.16 on 2025-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('motherboard_id', models.CharField(max_length=255)),
                ('hard_disk', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
    ]
