# Generated by Django 5.1.4 on 2025-01-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_taxdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('registration_type', models.CharField(max_length=100)),
                ('assessee_of_other_territory', models.CharField(max_length=100)),
                ('GSTIN_UIN', models.CharField(max_length=100)),
                ('periodicity_of_GSTR1', models.CharField(max_length=100)),
                ('gst_user_name', models.CharField(max_length=100)),
                ('mode_filing', models.CharField(max_length=100)),
                ('e_invoicing_applicable', models.CharField(max_length=100)),
                ('applicable_from_e_invoicing', models.DateField()),
                ('invoice_bill_from_place', models.CharField(max_length=100)),
                ('e_way_bill_applicable', models.CharField(max_length=100)),
                ('applicable_from_e_way_bill', models.DateField()),
                ('applicable_for_intrastate', models.CharField(max_length=100)),
            ],
        ),
    ]
