# Generated by Django 4.2.16 on 2025-02-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HardwareDetails',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='cpu',
            new_name='access_key',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='hard_disk',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='motherboard_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='random_key',
        ),
    ]
