# Generated by Django 5.1.4 on 2025-01-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_stockcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockgroup',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockcategory',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockgroup'),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='under',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockgroup'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='gst_applicability',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='opening_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='rate_of_duty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='rate_per_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='type_of_supply',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stockcategory'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unitcreation'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='value',
            field=models.FloatField(),
        ),
    ]
