# Generated by Django 4.2.16 on 2025-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_stockgroup_alias_stockitem_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dispatch_from', models.CharField(max_length=255)),
                ('ship_to', models.CharField(max_length=255)),
                ('transporter_name', models.CharField(default='None', max_length=255)),
                ('new_transport_for_shipment', models.CharField(blank=True, max_length=255)),
                ('transport_id', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('doc_lading_rr_airway_no', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('date_of_transport', models.DateField()),
            ],
        ),
    ]
