# Generated by Django 4.2.16 on 2025-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_usermodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='img',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
