# Generated by Django 4.2.16 on 2025-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ewaybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewaybill',
            name='doc_lading_rr_airway_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='new_transport_for_shipment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='vehicle_number',
            field=models.CharField(max_length=100),
        ),
    ]
