# Generated by Django 4.2.16 on 2025-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_ewaybill_doc_lading_rr_airway_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_no', models.CharField(max_length=100)),
                ('ack_date', models.DateField()),
                ('irn', models.CharField(max_length=100)),
                ('bill_to_place', models.CharField(max_length=255)),
                ('ship_to_place', models.CharField(max_length=255)),
            ],
        ),
    ]
