# Generated by Django 4.2.16 on 2025-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_productdetails_img_productdetails_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
