# Generated by Django 4.2.16 on 2025-03-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('gst_no', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_value', models.FloatField(default=0)),
                ('cgst_percentage', models.FloatField(default=0)),
                ('cgst_value', models.FloatField(default=0)),
                ('sgst_percentage', models.FloatField(default=0)),
                ('sgst_value', models.FloatField(default=0)),
                ('total_amount', models.FloatField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('total_amount_before_tax', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('total_cgst', models.FloatField(default=0)),
                ('total_sgst', models.FloatField(default=0)),
                ('grant_total', models.FloatField()),
                ('total_amount_2', models.FloatField()),
                ('received', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('sale_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customerlist',
            old_name='gst_number',
            new_name='gst_no',
        ),
        migrations.RenameField(
            model_name='customerlist',
            old_name='mobile_number',
            new_name='mobile_no',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
