# Generated by Django 4.2.16 on 2025-01-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_pricedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGstDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsn_sac_code', models.CharField(max_length=100)),
                ('cess_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cess_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_gst_details', to='myapp.productdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='PriceDetails',
        ),
    ]
