# Generated by Django 4.2.16 on 2025-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_sale_rename_gst_number_customerlist_gst_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='supplier_name',
            field=models.CharField(default='haniya', max_length=255),
            preserve_default=False,
        ),
    ]
