# Generated by Django 4.2.16 on 2025-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_stockdetails_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_code',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_model',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
