# Generated by Django 4.2.16 on 2025-01-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_brand_category_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='PriceGstDetails',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
