# Generated by Django 4.2.16 on 2025-01-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_productdetails_pricedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',

        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category'),
        ),
    ]
