# Generated by Django 4.2.16 on 2025-01-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_subcategory_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedetails',
            name='product',
        ),
        migrations.AlterField(
            model_name='pricedetails',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='myapp.productdetails'),
        ),
    ]
