# Generated by Django 4.2.16 on 2025-01-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_pricedetails_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedetails',
            old_name='product_name',
            new_name='product',
        ),
    ]
