# Generated by Django 4.2.16 on 2025-01-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_pricedetails_delete_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceDetails',
            new_name='ProductPriceDetails',
        ),
    ]
