# Generated by Django 4.2.16 on 2025-01-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPriceDetails',
            new_name='PriceDetails',
        ),
        migrations.RemoveField(
            model_name='stockcategory',
            name='under',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='under',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='units',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='StockCategory',
        ),
        migrations.DeleteModel(
            name='StockGroup',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='UnitCreation',
        ),
    ]
