# Generated by Django 4.2.16 on 2025-01-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_productpricedetails_pricedetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cess_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cess_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='myapp.category')),
            ],
        ),
    ]
