# Generated by Django 4.2.16 on 2025-01-27 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_gstdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.PositiveIntegerField()),
                ('opening_stock_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_stock_qty', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_details', to='myapp.productdetails')),
            ],
        ),
    ]
