# Generated by Django 4.2.16 on 2025-01-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_stockdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstdetails',
            name='cess_percentage',
        ),
        migrations.RemoveField(
            model_name='gstdetails',
            name='cess_value',
        ),
    ]
