# Generated by Django 4.2.16 on 2025-01-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_category_name_subcategory_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
