# Generated by Django 4.2.16 on 2025-01-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
