# Generated by Django 4.2.16 on 2025-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_rename_category_subcategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='category',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='category_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
