# Generated by Django 4.2.16 on 2025-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_productdetails_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='brand_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sub_category_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='unit',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
