# Generated by Django 4.2.16 on 2025-01-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_productdetails_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='customer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
