# Generated by Django 4.2.16 on 2025-01-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_productdetails_customer_id_productdetails_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='myapp.employee'),
        ),
    ]
