# Generated by Django 4.2.16 on 2025-02-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_customer_alter_productdetails_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_details', to='myapp.productdetails'),
        ),
    ]
