# Generated by Django 4.2.16 on 2025-02-01 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="The license key cannot contain the characters '0' or 'o'.", regex='^[A-NP-Za-np-z0-9]+$')])),
                ('expiry_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('hardware_signature', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_details', to='myapp.admin')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_details', to='myapp.subscriptionplan')),
            ],
        ),
    ]
