# Generated by Django 4.2.16 on 2025-02-01 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message="The license key cannot contain the characters '0' or 'o'.", regex='^[A-NP-Za-np-z0-9]+$')]),
        ),
    ]
