# Generated by Django 4.2.16 on 2025-01-10 07:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('financial_year_start', models.DateField()),
                ('financial_year_end', models.DateField()),
                ('gst_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('default_currency', models.CharField(max_length=10)),
                ('multi_currency_enabled', models.BooleanField(default=False)),
                ('multi_language_support', models.JSONField()),
                ('business_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('trading', 'Trading'), ('service', 'Service')], max_length=50)),
                ('data_locking_enabled', models.BooleanField(default=False)),
                ('lock_period_from', models.DateField(blank=True, null=True)),
                ('lock_period_to', models.DateField(blank=True, null=True)),
                ('default_email', models.EmailField(max_length=254)),
                ('default_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencySetting',
            fields=[
                ('currency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('default_currency', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Details.company')),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Details.branch')),
            ],
        ),
    ]
