# Generated by Django 4.2.16 on 2025-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='default_currency',
            new_name='base_currency',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='data_locking_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lock_period_from',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lock_period_to',
        ),
        migrations.RemoveField(
            model_name='company',
            name='multi_currency_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='multi_language_support',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fax_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mailing_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
