# Generated by Django 4.2.16 on 2025-01-13 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_rename_default_currency_company_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('default_currency', models.CharField(max_length=10)),
                ('multi_currency_enabled', models.BooleanField(default=False)),
                ('multi_language_support', models.JSONField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('trading', 'Trading'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20)),
                ('data_locking_enabled', models.BooleanField(default=False)),
                ('lock_period_from', models.DateField(blank=True, null=True)),
                ('lock_period_to', models.DateField(blank=True, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('default_phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
