# Generated by Django 4.2.16 on 2025-01-15 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('license_key', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="The license key cannot contain the characters '0' or 'o'.", regex='^[A-NP-Za-np-z0-9]+$')])),
                ('status', models.TextField(default='unverified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
