# Generated by Django 4.2.16 on 2025-01-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
