# Generated by Django 4.2.16 on 2025-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0006_emailotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='financial_year_end',
            new_name='books_beginning_from',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='financial_year_start',
            new_name='financial_year_begins_from',
        ),
        migrations.RemoveField(
            model_name='company',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='company',
            name='add_space_between_amount_and_symbol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='administrator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='decimal_places_for_amount_in_words',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='disallow_opening_in_educational_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='formal_name',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_decimal_places',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='repeat_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_amount_in_millions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='suffix_symbol_to_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='use_audit_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='use_security_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='word_representing_amount_after_decimal',
            field=models.CharField(default='paise', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
