# Generated by Django 4.2.16 on 2025-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0007_rename_financial_year_end_company_books_beginning_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('maintain_balances_bill_by_bill', models.BooleanField(default=False)),
                ('default_credit_period', models.IntegerField(blank=True, null=True)),
                ('check_credit_days_during_voucher_entry', models.BooleanField(default=False)),
                ('inventory_values_affected', models.BooleanField(default=False)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('mailing_address', models.TextField(null=True)),
                ('mailing_country', models.CharField(max_length=100, null=True)),
                ('mailing_state', models.CharField(max_length=100, null=True)),
                ('mailing_pincode', models.CharField(max_length=10, null=True)),
                ('provide_bank_details', models.BooleanField(default=False)),
                ('pan_it_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_type', models.CharField(choices=[('Regular', 'Regular'), ('Composition', 'Composition')], default='Regular', max_length=20)),
                ('gstin_uin', models.CharField(blank=True, max_length=15, null=True)),
                ('set_alter_gst_details', models.BooleanField(default=False)),
                ('gst_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
