# Generated by Django 4.2.16 on 2025-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0008_salesparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesparty',
            name='check_credit_days_during_voucher_entry',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
