# Generated by Django 4.2.16 on 2025-01-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0009_alter_salesparty_check_credit_days_during_voucher_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingVoucher',
            fields=[
                ('sales_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reference_no', models.CharField(max_length=50)),
                ('party_account_name', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales_ledger', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.TextField()),
            ],
        ),
    ]
