# Generated by Django 4.2.16 on 2025-01-20 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0010_accountingvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseParty',
            fields=[
                ('purchase_party_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('under_sales_party', models.CharField(default='Sales Party (Current Assets)', max_length=255)),
                ('maintain_balances', models.BooleanField(default=False)),
                ('default_credit_period', models.PositiveIntegerField(blank=True, null=True)),
                ('check_credit_days', models.BooleanField(blank=True, null=True)),
                ('inventory_values_affected', models.BooleanField(default=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('mailing_address', models.TextField(null=True)),
                ('mailing_country', models.CharField(max_length=100, null=True)),
                ('mailing_state', models.CharField(max_length=100, null=True)),
                ('mailing_pincode', models.CharField(max_length=10, null=True)),
                ('provide_bank_details', models.BooleanField(default=False)),
                ('pan_it_no', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_type', models.CharField(default='Regular', max_length=50)),
                ('gstin_uin', models.CharField(blank=True, max_length=15, null=True)),
                ('set_alter_gst_details', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
