# Generated by Django 4.2.16 on 2025-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0011_purchaseparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesparty',
            name='check_credit_days_during_voucher_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
