# Generated by Django 4.2.16 on 2025-01-20 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0012_alter_salesparty_check_credit_days_during_voucher_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_values_affected', models.BooleanField(default=False)),
                ('type_of_ledger', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Discount', 'Discount'), ('Invoice Rounding', 'Invoice Rounding')], default='Not Applicable', max_length=20)),
                ('rounding_method', models.CharField(blank=True, max_length=50, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, null=True)),
                ('mailing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('provide_bank_details', models.BooleanField(default=False)),
                ('pan_it_no', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseparty',
            name='under_sales_party',
        ),
    ]
