# Generated by Django 4.2.16 on 2025-01-21 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0013_purchaseledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
                ('SalesLedger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('under', models.CharField(default='Sales Ledger', max_length=255)),
                ('inventory_values_affected', models.BooleanField(default=False)),
                ('type_of_salesLeger', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Discount', 'Discount'), ('Invoice Rounding', 'Invoice Rounding')], default='Not Applicable', max_length=50)),
                ('rounding_method', models.CharField(blank=True, max_length=255, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, null=True)),
                ('mailing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('provide_bank_details', models.BooleanField(default=False)),
                ('pan_it_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseledger',
            name='under',
            field=models.CharField(default='Purchase Ledger', max_length=255),
        ),
    ]
