# Generated by Django 4.2.16 on 2025-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0014_salesledger_purchaseledger_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('purchase_no', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_invoice_no', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('party_account_name', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_ledger', models.CharField(max_length=255)),
                ('narration', models.TextField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
