# Generated by Django 4.2.16 on 2025-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0015_purchasevoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=255)),
                ('cur_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('particulars', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
