# Generated by Django 4.2.16 on 2025-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0016_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('under', models.CharField(default='Cash-in-Hand (Current Assets)', max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('mailing_address', models.TextField()),
                ('provide_bank_details', models.BooleanField(default=False)),
                ('bank_details_for', models.CharField(blank=True, max_length=255, null=True)),
                ('Account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_it_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
