# Generated by Django 4.2.16 on 2025-02-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0017_cashinhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseparty',
            name='journal_direct_purchase_to_sales_clearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseparty',
            name='journal_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseparty',
            name='journal_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseparty',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseparty',
            name='purchase_ledger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseparty',
            name='under_sundry_creditors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='journal_direct_purchase_to_sales_clearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='journal_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='journal_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='sales_ledger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesparty',
            name='under_sundry_debtors',
            field=models.BooleanField(default=False),
        ),
    ]
