# Generated by Django 4.2.16 on 2025-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0018_purchaseparty_journal_direct_purchase_to_sales_clearance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingvoucher',
            old_name='sales_ledger',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='accountingvoucher',
            old_name='amount',
            new_name='grand_total',
        ),
        migrations.RemoveField(
            model_name='accountingvoucher',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='accountingvoucher',
            name='per',
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='billing_shipping_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='e_invoice_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='sales_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='accountingvoucher',
            name='total_amount_before_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
