from django.urls import path
from Myapp import views

urlpatterns = [
    path('GST/add', views.addGst, name='AddGst'),
    path('GST/get', views.GstGet, name='GstGet'),
    path('GST/update',views.update_gst, name='update_gst'),
    path('GST/delete', views.delete_gst, name='delete_gst'),
    path('stock/group/add', views.addStockGroup, name='addStockGroup'),
    path('stock/group/get', views.getStockGroup, name='getStockGroup'),
    path('stock/group/update', views.update_stock_group, name='update_stock_group'),
    path('stock/group/delete', views.delete_stock_group, name='delete_stock_group'),
    path('stock/group/gstdetail/add', views.addStockGroupTaxDetails, name='addStockgroupGst'),
    path('stock/group/gstdetail/get', views.getGroupTaxDetails, name='getGroupTaxDetails'),
    path('stock/group/gstdetail/update', views.updateGroupTaxDetails, name='updateGroupTaxDetails'),
    path('stock/group/gstdetail/delete', views.deleteGroupTaxDetails, name='deleteGroupTaxDetails'),
    path('stock/category/add', views.addStockCategory, name='addStockCategory'),
    path('stock/category/get', views.get_category, name='get_category'),
    path('stock/category/update', views.update_category, name='update_category'),
    path('stock/category/delete', views.delete_category, name='delete_category'),
    path('stock/item/add', views.add_stock_item, name='add_stock_item'),
    path('stock/item/get', views.StockItemget, name='StockItemget'),
    path('stock/item/update', views.update_stock_item, name='update_stock_item'),
    path('stock/item/delete', views.delete_stock_item, name='delete_stock_item'),
    path('unit/add', views.add_unit_creation, name='add_unit_creation'),
    path('unit/get', views.get_unit, name='get_unit'),
    path('unit/update', views.update_unit, name='update_unit'),
    path('unit/delete', views. delete_unit, name=' delete_unit'),
    path('productdetails/add', views.add_product, name=' add_product'),
    path('productdetails/get', views.get_product, name=' get_product'),
    path('productdetails/update', views.update_product, name=' update_product'),
    path('productdetails/delete', views.delete_product, name=' delete_product'),
    path('other_details/add', views.add_other_details, name=' add_other_details'),
    path('other_details/get', views.get_other_details, name=' get_other_details'),
    path('other_details/update', views.update_other_details, name='update_other_details'),
    path('other_details/delete', views.delete_other_details, name='delete_other_details'),
    path('productsetting/add', views.add_product_settings, name='add_product_settings'),
    path('productsetting/get', views.get_product_settings, name='get_product_settings'),
    path('productsetting/update', views.update_product_settings, name='update_product_settings'),
    path('productsetting/delete', views.delete_product_settings, name='delete_product_settings'),
    path('product_description/add', views.add_product_description, name='add_product_description'),
    path('product_description/get', views.get_product_description, name='get_product_description'),
    path('product_description/update', views.update_product_description, name='update_product_description'),
    path('product_description/delete', views.delete_product_description, name='delete_product_description'),
]
